name = "rednav"
compatibility_date = "2025-08-26"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23livpf0oyUf9fzc4c"
GITHUB_OWNER = "PURE281"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://rednav.pages.dev/api/authh"
NEXT_PUBLIC_API_URL="https://rednav.pages.dev/api/auth"

